/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.html',
    './user/**/*.html',
    './obgyn/**/*.html',
    './js/**/*.js',
    './css/**/*.css',
  ],
  safelist: [
    'pcode-diagnostic-bento',
    'pcode-diagnostic-grid',
    'pcode-diagnostic-title',
    'pcode-diagnostic-muted',
    'pcode-diagnostic-scroll',
    'pcode-diagnostic-results-panel',
    'pcode-diagnostic-results-panel.is-revealed',
    'pcode-unit-pill',
    'pcode-unit-pill__btn',
    'pcb-cm-cell',
    'pcb-cm-cell__count',
    'pcb-cm-cell__type',
    'pcb-cm-bento--purple',
    'pcb-cm-bento--blue',
    'pcb-cm-bento-host--purple',
    'pcb-cm-bento-host--blue',
    'pcode-bento-metrics-grid--fluid',
    'pcode-bento-metrics-grid--two',
    'pcode-mp-stat-grid',
    'pcode-mp-split-cols',
    'pcode-mp-footnote',
    'pcode-mp-hero-desc',
    'pcode-diagnosis-chip--pending',
    'pcode-diagnosis-chip--positive',
    'pcode-diagnosis-chip--negative',
    'pcode-diagnosis-chip--borderline',
    'pcode-diagnosis-chip__label',
    'pcode-diagnosis-chip__count',
    'motion-safe:animate-fade-in',
    'dark:shadow-[0_0_20px_rgba(168,85,247,0.15)]',
    'dark:shadow-[0_0_28px_rgba(168,85,247,0.22)]',
    'dark:border-purple-500/20',
    'dark:animate-aura-spread',
    'animate-aura-spread',
    'pcode-glass-aura',
    'pcode-glass-aura__blob',
    'pcode-glass-aura__blob--purple',
    'pcode-glass-aura__blob--indigo',
    'opacity-0',
    'scale-75',
    'dark:opacity-100',
    'dark:scale-100',
    // Responsive layout classes
    'md:flex-row',
    'md:w-1/2',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    // Green color gradients
    'from-green-500',
    'to-green-600',
    'hover:from-green-600',
    'hover:to-green-700',
    // Blue color gradients
    'from-blue-500',
    'to-blue-600',
    'hover:from-blue-600',
    'hover:to-blue-700',
    // Purple colors (already used)
    'from-purple-600',
    'to-purple-700',
    'hover:from-purple-700',
    'hover:to-purple-800',
  ],
  theme: {
    extend: {
      colors: {
        medical: {
          purple: '#6B46C1',
          light: '#8B5CF6',
          soft: '#A78BFA',
          success: '#10B981',
          warning: '#F59E0B',
          error: '#EF4444',
          info: '#3B82F6',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'pulse-slow': 'pulse 3s infinite',
        'aura-spread': 'aura-expand 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'aura-expand': {
          '0%': { transform: 'scale(0.8)', opacity: '0', filter: 'blur(60px)' },
          '50%': { transform: 'scale(1.05)', opacity: '0.7', filter: 'blur(80px)' },
          '100%': { transform: 'scale(1)', opacity: '1', filter: 'blur(70px)' },
        },
      },
    },
  },
  plugins: [],
}